# Site settings
title: 2nd Workshop on E-science ReseaRch leading tO negative Results
acronym: ERROR 2022

markdown: kramdown
enable-mathjax: yes

# SEO
author:
  name: Workflows Community Initiative
  twitter: WorkflowsCI
  image: https://workflows.community/favicon.ico
twitter:
  username: WorkflowsCI
  card: summary_large_image
social:
  name: Workflows Community Initiative
  links: 
    - https://twitter.com/WorkflowsCI
defaults:
  - scope:
      path: ""
    values:
      image: https://workflows.community/images/wci-default-card.png

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.

exclude:
  - .jekyll-cache
  - README.md
  - LICENSE
